Vagrant.configure("2") do |config|
  config.vm.define "gitlab" do |web|
    web.vm.box = "ubuntu/focal64"
    web.vm.box_download_insecure = true
    web.vm.network "public_network", bridge: "Realtek Gaming GbE Family Controller", ip: "192.168.2.120"
    config.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 4
    end
  end

    config.vm.define "runtimes" do |web|
      web.vm.box = "ubuntu/focal64"
      web.vm.box_download_insecure = true
      web.vm.network "public_network", bridge: "Realtek Gaming GbE Family Controller", ip: "192.168.2.121"
      config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 4
      end
  end
end

